name: CI
on:
  push:
    branches-ignore:
      - "releases/**"
  pull_request:
    branches-ignore:
      - "releases/**"
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 16
        arch:
          - x64
          - arm64
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Setup node (node=${{ matrix.node-version }}, arch=${{ matrix.arch }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV
          echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Configure build
        run: ./node_modules/.bin/node-pre-gyp configure --target_arch=${{ env.TARGET }}

      - name: Build binaries
        run: ./node_modules/.bin/node-pre-gyp build --target_arch=${{ env.TARGET }}

      - name: Package prebuilt binaries
        run: ./node_modules/.bin/node-pre-gyp package --target_arch=${{ env.TARGET }}

      # - name: Add distutils
      #   run: pip install setuptools

      # - run: npm run build:macos
      # - run: npm run test-ci
